# Generated by Django 4.2.4 on 2024-02-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='value', to='item.item'),
        ),
        migrations.AlterField(
            model_name='value',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='value', to='item.category'),
        ),
    ]
