# Generated by Django 4.2.4 on 2024-02-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_value_item_alter_value_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_values', to='item.category'),
        ),
        migrations.AlterField(
            model_name='value',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_values', to='item.item'),
        ),
    ]
